### ISSUE TITLE
Search term hard to read

### ISSUE THREAD

**Issue by marcelhekking** [wangweixuan/yithemes#8] opened 2021-06-22 05:30 UTC
Because of the used colors, the part of the search term (after CTRL-SHIFT-P) is hard to read:
![image](https://user-images.githubusercontent.com/946241/122868763-b2b20e00-d32b-11eb-9392-ebe56b6f3eb0.png)

**Comment by wangweixuan** [comment] 2021-06-23 14:59
Thanks for the feedback! The issue is fixed in version 0.16.0. Background of the selected item is now grey, the same as in Atom One Dark.

**Closed as completed** 2021-06-24 15:52 UTC

**Comment by marcelhekking** [comment] 2021-06-26 13:22
Thanx for the fix!
